### PR TITLE
lua pktin processing 

### PR DESCRIPTION
**Pull request by harshsin**
Reviewer: @rlane

### CODE REVIEW

**Comment by harshsin** [comment]
Changed it to return a boolean instead.

**Comment by rlane** [comment]
What's the reason for returning the result in an FFI object instead of just having `sandbox.pktin` return a boolean?

**Comment by harshsin** [comment]
Done

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/ivs_pull_req/24/
Test PASSed.

**Pull request merged**
