### PR TITLE
update loxigen-artifacts

### PR DESCRIPTION
**Pull request by harshsin**
Reviewer: @harshsin

* submodules/loxigen-artifacts fae5788...3cea6c3 (5):
  > Artifacts from https://github.com/floodlight/loxigen/compare/88dd8aeae8cc917fcadfd9eb0feaf8679a907f40...3e14dd961ba8d22a211bed2cc8958f036be71507
  > Artifacts from https://github.com/floodlight/loxigen/compare/0c6269506316c98e1233b95e9c86d7303330bc75...88dd8aeae8cc917fcadfd9eb0feaf8679a907f40
  > Artifacts from https://github.com/floodlight/loxigen/compare/fa56f26426e18cbb4168750850e5363473e0a969...0c6269506316c98e1233b95e9c86d7303330bc75
  > Artifacts from https://github.com/floodlight/loxigen/compare/53192c6f5e9f1388d1334dda75a2eb0b3fc87014...fa56f26426e18cbb4168750850e5363473e0a969
  > Artifacts from https://github.com/floodlight/loxigen/compare/b613d53642d9406a92b109e975cc7359083a9a30...53192c6f5e9f1388d1334dda75a2eb0b3fc87014

### CODE REVIEW

**Comment by harshsin** [comment]
SELF-ACK

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/ivs_pull_req/58/
Test FAILed.

**Comment by harshsin** [comment]
RETRY

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/ivs_pull_req/59/
Test FAILed.

**Comment by harshsin** [comment]
Jenkins worker VM is slow and OFTest timed out waiting for the hashtable benchmark to complete. Trying again.

ACK

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/ivs_pull_req/60/
Test FAILed.

**Comment by rlane** [comment]
I increased the OFTest timeout.

ACK

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/ivs_pull_req/61/
Test PASSed.

**Pull request merged**
