### PR TITLE
Use new OpenFlow message to upload Lua

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @harshsin 

We previously used a gentable for this purpose, which had a 64K limit per file and didn't support atomic uploads.

### CODE REVIEW

**Comment by rlane** [comment]
I pushed a new commit updating loxigen-artifacts to get the new messages.

**Comment by harshsin** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://trusty1/abat/2015.01.05.2350-m.ivs.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://trusty1/abat/2015.01.05.2350-m.ivs.master/abat.log
/cc @rlane

**Pull request merged**
