### PR TITLE
OVSDriver: read multiple multicast messages per trip through the event loop

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @harshsin

### CODE REVIEW

**Comment by harshsin** [comment]
We can get rid of explicitly setting the socket to non-blocking from the callers of ind_ovs_create_nlsock() now.

**Comment by harshsin** [comment]
LGTM. Minor comment.

**Comment by rlane** [comment]
Thanks for the review. I removed the redundant set-nonblocking calls.

ACK

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/ivs_pull_req/7/
Test PASSed.

**Pull request merged**
