### PR TITLE
set inband control queue priority

### PR DESCRIPTION
**Pull request by harshsin**
Reviewer: @rlane

### CODE REVIEW

**Comment by rlane** [comment]
Instead of a public global variable, make the variable static and add an API to set it.

**Comment by harshsin** [comment]
Thanks for taking a look. Added the api to set the priority.

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://trusty1/abat/2015.02.02.2331-m.ivs.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://trusty1/abat/2015.02.02.2331-m.ivs.master/abat.log
/cc @rlane

**Pull request closed without merging**
