### PR TITLE
Packet trace

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @harshsin 

This pull request adds a new "trace" command to ivs-ctl. With this command you can watch the forwarding decisions being made in real time. This is extremely useful for debugging issues where packets aren't being forwarded as expected.

This code is designed to have minimal performance impact when no trace clients are connected or when no filters match a given packet. It should be easy to add new types of filters besides just port number.

Usage:

    ivs-ctl trace port 6 # Show all packets from port 6
    ivs-ctl trace # Show all packets

### CODE REVIEW

**Comment by harshsin** [comment]
Merge conflicts

**Comment by rlane** [comment]
Fixed merge conflicts.

**Comment by harshsin** [comment]
Looks Good. One minor comment.

**Comment by rlane** [comment]
Thanks for the review.

SELF-ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://trusty1/abat/2015.03.31.1803-m.ivs.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://trusty1/abat/2015.03.31.1803-m.ivs.master/abat.log
/cc @rlane

**Pull request merged**
