### PR TITLE
blacklist a few tests

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: trivial

We want Jenkins to reject any pull requests that cause new test failures.

### CODE REVIEW

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/ivs_pull_req/41/
Test FAILed.

**Comment by rlane** [comment]
JENKINS-RETRY

**Comment by rlane** [comment]
ACK

**Comment by bsn-abat** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.bigswitch.com//job/ivs_pull_req/42/
Test PASSed.

**Pull request merged**
