### PR TITLE
Lua pipeline improvements

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: @harshsin 

These changes improve the sandbox to the point where I'm comfortable enabling the Lua pipeline by default. Uploaded code should no longer be able to access FFI pointers or freed memory.

Because our hashtable uses the FFI for performance I'm moving it to the builtin Lua code.

### CODE REVIEW

**Comment by harshsin** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://trusty1/abat/2015.01.22.2032-m.ivs.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in ivs/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://trusty1/abat/2015.01.22.2032-m.ivs.master/abat.log
/cc @rlane

**Comment by rlane** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://trusty1/abat/2015.01.22.2320-m.ivs.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://trusty1/abat/2015.01.22.2320-m.ivs.master/abat.log
/cc @rlane

**Pull request merged**
